
/**
 * A map from BVH bone name to VRM Humanoid bone name
 */
export const bvhVRMRigMap = {
	'bones[Hips]': 'hips',
	'bones[Spine]': 'spine',
	'bones[Spine]': 'chest',
	'bones[Spine1]': 'upperChest',
	'bones[Neck]': 'neck',
	'bones[Head]': 'head',
	'bones[LeftShoulder]': 'leftShoulder',
	'bones[LeftArm]': 'leftUpperArm',
	'bones[LeftForeArm]': 'leftLowerArm',
	'bones[LeftHand]': 'leftHand',
	'bones[LThumb]': 'leftThumbMetacarpal',
	// mixamorigLeftHandThumb2: 'leftThumbProximal',
	// mixamorigLeftHandThumb3: 'leftThumbDistal',
	// mixamorigLeftHandIndex1: 'leftIndexProximal',
	// mixamorigLeftHandIndex2: 'leftIndexIntermediate',
	// mixamorigLeftHandIndex3: 'leftIndexDistal',
	// mixamorigLeftHandMiddle1: 'leftMiddleProximal',
	// mixamorigLeftHandMiddle2: 'leftMiddleIntermediate',
	// mixamorigLeftHandMiddle3: 'leftMiddleDistal',
	// mixamorigLeftHandRing1: 'leftRingProximal',
	// mixamorigLeftHandRing2: 'leftRingIntermediate',
	// mixamorigLeftHandRing3: 'leftRingDistal',
	// mixamorigLeftHandPinky1: 'leftLittleProximal',
	// mixamorigLeftHandPinky2: 'leftLittleIntermediate',
	// mixamorigLeftHandPinky3: 'leftLittleDistal',
	'bones[RightShoulder]': 'rightShoulder',
	'bones[RightArm]': 'rightUpperArm',
	'bones[RightForeArm]': 'rightLowerArm',
	'bones[RightHand]': 'rightHand',
	// mixamorigRightHandPinky1: 'rightLittleProximal',
	// mixamorigRightHandPinky2: 'rightLittleIntermediate',
	// mixamorigRightHandPinky3: 'rightLittleDistal',
	// mixamorigRightHandRing1: 'rightRingProximal',
	// mixamorigRightHandRing2: 'rightRingIntermediate',
	// mixamorigRightHandRing3: 'rightRingDistal',
	// mixamorigRightHandMiddle1: 'rightMiddleProximal',
	// mixamorigRightHandMiddle2: 'rightMiddleIntermediate',
	// mixamorigRightHandMiddle3: 'rightMiddleDistal',
	// mixamorigRightHandIndex1: 'rightIndexProximal',
	// mixamorigRightHandIndex2: 'rightIndexIntermediate',
	// mixamorigRightHandIndex3: 'rightIndexDistal',
	'bones[RThumb]': 'rightThumbMetacarpal',
	'bones[LeftUpLeg]': 'leftUpperLeg',
	'bones[LeftLeg]': 'rightLowerLeg',
	'bones[LeftFoot]': 'leftFoot',
	'bones[LeftToeBase]': 'leftToes',
	'bones[RightUpLeg]': 'rightUpperLeg',
	'bones[RightLeg]': 'rightLowerLeg',
	'bones[RightFoot]': 'rightFoot',
	'bones[RightToeBase]': 'rightToes',
};

// ( 62 )[
// 'bones[Hips]',
// 'bones[Hips]',
// 'bones[LHipJoint]',
// 'bones[LHipJoint]',
// 'bones[LeftUpLeg]',
// 'bones[LeftUpLeg]',
// 'bones[LeftLeg]',
// 'bones[LeftLeg]',
// 'bones[LeftFoot]',
// 'bones[LeftFoot]',
// 'bones[LeftToeBase]',
// 'bones[LeftToeBase]',
// 'bones[RHipJoint]',
// 'bones[RHipJoint]',
// 'bones[RightUpLeg]',
// 'bones[RightUpLeg]',
// 'bones[RightLeg]',
// 'bones[RightLeg]',
// 'bones[RightFoot]',
// 'bones[RightFoot]',
// 'bones[RightToeBase]',
// 'bones[RightToeBase]',
// 'bones[LowerBack]',
// 'bones[LowerBack]',
// 'bones[Spine]',
// 'bones[Spine]',
// 'bones[Spine1]',
// 'bones[Spine1]',
// 'bones[Neck]',
// 'bones[Neck]',
// 'bones[Neck1]',
// 'bones[Neck1]',
// 'bones[Head]',
// 'bones[Head]',
// 'bones[LeftShoulder]',
// 'bones[LeftShoulder]',
// 'bones[LeftArm]',
// 'bones[LeftArm]',
// 'bones[LeftForeArm]',
// 'bones[LeftForeArm]',
// 'bones[LeftHand]',
// 'bones[LeftHand]',
// 'bones[LeftFingerBase]',
// 'bones[LeftFingerBase]',
// 'bones[LFingers]',
// 'bones[LFingers]',
// 'bones[LThumb]',
// 'bones[LThumb]',
// 'bones[RightShoulder]',
// 'bones[RightShoulder]',
// 'bones[RightArm]',
// 'bones[RightArm]',
// 'bones[RightForeArm]',
// 'bones[RightForeArm]',
// 'bones[RightHand]',
// 'bones[RightHand]',
// 'bones[RightFingerBase]',
// 'bones[RightFingerBase]',
// 'bones[RFingers]',
// 'bones[RFingers]',
// 'bones[RThumb]',
// 'bones[RThumb]' ];
