/**
 * A map from an autogenerated fbx file from a mocap bvh file to VRM Humanoid bone name
 */
export const motionVRMRigMap = {
	LHipJoint: 'hips',
	RHipJoint: 'hips',
	Spine: 'spine',
	Spine1: 'chest',
	// mixamorigSpine2: 'upperChest',
	Neck: 'neck',
	Head: 'head',
	LeftShoulder: 'leftShoulder',
	LeftArm: 'leftUpperArm',
	LeftForeArm: 'leftLowerArm',
	LeftHand: 'leftHand',
	LThumb: 'leftThumbMetacarpal',
	// mixamorigLeftHandThumb2: 'leftThumbProximal',
	// mixamorigLeftHandThumb3: 'leftThumbDistal',
	LeftHandIndex1: 'leftIndexProximal',
	// mixamorigLeftHandIndex2: 'leftIndexIntermediate',
	// mixamorigLeftHandIndex3: 'leftIndexDistal',
	// mixamorigLeftHandMiddle1: 'leftMiddleProximal',
	// mixamorigLeftHandMiddle2: 'leftMiddleIntermediate',
	// mixamorigLeftHandMiddle3: 'leftMiddleDistal',
	// mixamorigLeftHandRing1: 'leftRingProximal',
	// mixamorigLeftHandRing2: 'leftRingIntermediate',
	// mixamorigLeftHandRing3: 'leftRingDistal',
	// mixamorigLeftHandPinky1: 'leftLittleProximal',
	// mixamorigLeftHandPinky2: 'leftLittleIntermediate',
	// mixamorigLeftHandPinky3: 'leftLittleDistal',
	RightShoulder: 'rightShoulder',
	RightArm: 'rightUpperArm',
	RightForeArm: 'rightLowerArm',
	RightHand: 'rightHand',
	// mixamorigRightHandPinky1: 'rightLittleProximal',
	// mixamorigRightHandPinky2: 'rightLittleIntermediate',
	// mixamorigRightHandPinky3: 'rightLittleDistal',
	// mixamorigRightHandRing1: 'rightRingProximal',
	// mixamorigRightHandRing2: 'rightRingIntermediate',
	// mixamorigRightHandRing3: 'rightRingDistal',
	// mixamorigRightHandMiddle1: 'rightMiddleProximal',
	// mixamorigRightHandMiddle2: 'rightMiddleIntermediate',
	// mixamorigRightHandMiddle3: 'rightMiddleDistal',
	RightHandIndex1: 'rightIndexProximal',
	// mixamorigRightHandIndex2: 'rightIndexIntermediate',
	// mixamorigRightHandIndex3: 'rightIndexDistal',
	RThumb: 'rightThumbMetacarpal',
	// mixamorigRightHandThumb2: 'rightThumbProximal',
	// mixamorigRightHandThumb3: 'rightThumbDistal',
	LeftUpLeg: 'leftUpperLeg',
	LeftLeg: 'leftLowerLeg',
	LeftFoot: 'leftFoot',
	LeftToeBase: 'leftToes',
	RightUpLeg: 'rightUpperLeg',
	RightLeg: 'rightLowerLeg',
	RightFoot: 'rightFoot',
	RightToeBase: 'rightToes',
};

// ALL BONES

// let bones = [];
// clip.tracks.forEach(element => {
//   if(!bones.includes(element.name.split(".")[0])) {
//     bones.push(element.name.split(".")[0])
//   }
// });
// console.log(bones)

// 0: 'LHipJoint'
// 1: 'LeftUpLeg'
// 2: 'LeftLeg'
// 3: 'LeftFoot'
// 4: 'LeftToeBase'
// 5: 'RHipJoint'
// 6: 'RightUpLeg'
// 7: 'RightLeg'
// 8: 'RightFoot'
// 9: 'RightToeBase'
// 10: 'LowerBack'
// 11: 'Spine'
// 12: 'Spine1'
// 13: 'Neck'
// 14: 'Neck1'
// 15: 'Head'
// 16: 'LeftShoulder'
// 17: 'LeftArm'
// 18: 'LeftForeArm'
// 19: 'LeftHand'
// 20: 'LeftFingerBase'
// 21: 'LeftHandIndex1'
// 22: 'LThumb'
// 23: 'RightShoulder'
// 24: 'RightArm'
// 25: 'RightForeArm'
// 26: 'RightHand'
// 27: 'RightFingerBase'
// 28: 'RightHandIndex1'
// 29: 'RThumb'
